import { Poppins,Inter } from "next/font/google";
import "./globals.css";


const poppins = Poppins({
  weight:['100','200','300','400','500','600','700','800','900'],
  subsets:['latin'],
  variable:'--font-poppins',
  fontSynthesis:'none',
  grayscale:'0',
})

const inter = Inter({
  weight:['100','200','300','400','500','600','700','800','900'],
  subsets:['latin'],
  variable:'--font-inter',
  fontSynthesis:'none',
  grayscale:'0',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
